// <auto-generated />
using System;
using GodScheduler.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GodScheduler.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123163454_AddAssignedWorkerId")]
    partial class AddAssignedWorkerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GodScheduler.Api.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("CargoName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("cargo_name");

                    b.Property<int>("ConfFlg")
                        .HasColumnType("int")
                        .HasColumnName("conf_flg");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("e_time");

                    b.Property<string>("Quantity")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("quantity");

                    b.Property<string>("RequiredSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("required_skill");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("s_time");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("work_date");

                    b.Property<string>("WorkName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("work_name");

                    b.Property<string>("WorkPlace")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("work_place");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("GodScheduler.Api.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCd")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("branch_cd");

                    b.Property<int>("CompetenceBhh")
                        .HasColumnType("int")
                        .HasColumnName("competence_bhh");

                    b.Property<int>("CompetenceWwm")
                        .HasColumnType("int")
                        .HasColumnName("competence_wwm");

                    b.Property<string>("CreatedUid")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("created_uid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("s_name");

                    b.HasKey("Id");

                    b.ToTable("Wokers");
                });
#pragma warning restore 612, 618
        }
    }
}
